# Generated by Django 4.1 on 2022-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontenjan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hemsire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('kodu', models.CharField(max_length=10)),
                ('sbkodu', models.CharField(max_length=7)),
                ('kurumadı', models.CharField(max_length=70)),
                ('sehir', models.CharField(max_length=17)),
                ('sayi', models.CharField(max_length=17)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ebe',
            name='kodu',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ebe',
            name='kurumadı',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ebe',
            name='sayi',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='ebe',
            name='sbkodu',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='ebe',
            name='sehir',
            field=models.CharField(max_length=17),
        ),
    ]
